### ISSUE TITLE
weird output from to_pinyin

### ISSUE THREAD

**Issue by brunovandamme** [tsroten/dragonmapper#10]
The following code
>    print dragonmapper.hanzi.to_pinyin(u'女')
>    print dragonmapper.hanzi.to_pinyin(u'女人')

outputs:
>    n̈ǔ
>    nǚren

where i think it should be:
>    nǚ
>    nǚren

**Comment by tsroten** [comment]
@brunovandamme Thanks for pointing out this bug. Not sure how that data slipped in there.
