### ISSUE TITLE
Wrong to_pinyin

### ISSUE THREAD

**Issue by brunovandamme** [tsroten/dragonmapper#14]
print hanzi.to_pinyin(u'绿')

outputs l̈ù
but should be lǜ

**Comment by mthewissen** [comment]
Same goes for 女 and other words containing a 'u' that both has an intonation and umlaut on it

**Comment by brunovandamme** [comment]
Pinyin of 女 was already fixed few months ago. See #10.

**Comment by mthewissen** [comment]
Oh my bad. I wasn't using the develop branch yet. Seems related though.

**Comment by ham1** [comment]
Looking at the data, quite a few characters map to `l̈ù`. Is this always incorrect?
Should 绿 only be `lǜ`?

```
虑	l̈ù/bì/lǜ
綠	l̈ù/lǜ
律	l̈ù/lǜ
绿	l̈ù/lǜ
慮	l̈ù/lǜ/lǘ
率	l̈ù/shuài/lǜ/lüe
```

**Comment by brunovandamme** [comment]
I'm no expert on this, but I think l̈ù is always incorrect. 
I have never seen the umlaut on any other letter but 'u' in pinyin.

**Comment by tsroten** [comment]
@brunovandamme Thanks for reporting this! I've gone ahead and fixed it. I'll have a new release out shortly.

**Comment by tsroten** [comment]
Ok, this is now on PyPi. Thanks again!
