### ISSUE TITLE
accented_to_numbered() not working for 'ai' syllable

### ISSUE THREAD

**Issue by bearnun** [tsroten/dragonmapper#15]
print(accented_to_numbered("aī"))
print(accented_to_numbered("aí"))
print(accented_to_numbered("aǐ"))
print(accented_to_numbered("aì"))
print(accented_to_numbered("ai"))

produces:

a5ī
a5í
a5ǐ
a5ì
ai5

**Comment by bearnun** [comment]
Note: accented_syllable_to_numbered() for 'aì'/'aǐ DOES work...

**Comment by tsroten** [comment]
@bearnun Thanks for using Dragon Mapper! I think you might have your tone mark on the wrong vowel. It should be:
`āi`
`ái`
`ǎi`
`ài`

Here are [the tone placement rules](https://en.wikipedia.org/wiki/Pinyin#Rules_for_placing_the_tone_mark). I hope that helps!

**Comment by bearnun** [comment]
That was a silly mistake on my part...Must have been a late night or something, ha.  

Thanks for making dragonmapper! :D
